//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.Awesome.Infra.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitHub.Awesome.Infra.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HTTP_VERB_KEY {
            get {
                return ResourceManager.GetString("HTTP_VERB_KEY", resourceCulture);
            }
        }
        
        public static string REST_API_CORE_BASE_ADDRESS {
            get {
                return ResourceManager.GetString("REST_API_CORE_BASE_ADDRESS", resourceCulture);
            }
        }
        
        public static string STATUS_CODE_BAD_REQUEST {
            get {
                return ResourceManager.GetString("STATUS_CODE_BAD_REQUEST", resourceCulture);
            }
        }
        
        public static string STATUS_CODE_INTERNAL_SERVER_ERROR {
            get {
                return ResourceManager.GetString("STATUS_CODE_INTERNAL_SERVER_ERROR", resourceCulture);
            }
        }
        
        public static string LABEL_REPOSITORIES {
            get {
                return ResourceManager.GetString("LABEL_REPOSITORIES", resourceCulture);
            }
        }
        
        public static string LABEL_ABOUT {
            get {
                return ResourceManager.GetString("LABEL_ABOUT", resourceCulture);
            }
        }
        
        public static string LABEL_APP {
            get {
                return ResourceManager.GetString("LABEL_APP", resourceCulture);
            }
        }
        
        public static string LABEL_COMPANY {
            get {
                return ResourceManager.GetString("LABEL_COMPANY", resourceCulture);
            }
        }
        
        public static string LABEL_WAITING {
            get {
                return ResourceManager.GetString("LABEL_WAITING", resourceCulture);
            }
        }
        
        public static string LABEL_WARNING {
            get {
                return ResourceManager.GetString("LABEL_WARNING", resourceCulture);
            }
        }
        
        public static string LABEL_OK {
            get {
                return ResourceManager.GetString("LABEL_OK", resourceCulture);
            }
        }
        
        public static string LABEL_GOTIT {
            get {
                return ResourceManager.GetString("LABEL_GOTIT", resourceCulture);
            }
        }
        
        public static string LABEL_AUTHOR {
            get {
                return ResourceManager.GetString("LABEL_AUTHOR", resourceCulture);
            }
        }
        
        public static string LABEL_CREATEDBY {
            get {
                return ResourceManager.GetString("LABEL_CREATEDBY", resourceCulture);
            }
        }
        
        public static string LABEL_AUTHOR_TITLE {
            get {
                return ResourceManager.GetString("LABEL_AUTHOR_TITLE", resourceCulture);
            }
        }
        
        public static string VALIDATION_PAGING_CURRENT_POSITION {
            get {
                return ResourceManager.GetString("VALIDATION_PAGING_CURRENT_POSITION", resourceCulture);
            }
        }
        
        public static string LABEL_LINKEDIN {
            get {
                return ResourceManager.GetString("LABEL_LINKEDIN", resourceCulture);
            }
        }
    }
}
